routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });

Route::resource('/', 'PostsController');
Route::post('home','PostsController@postindex');
Route::get('detail/{id}','PostsdetailController@detail');
Route::get('Trending','PostsdetailController@show');
Route::resource('upload', 'UploadPostsController');



// admin panel
Route::get('admin', function () { return view('admin.dashboard'); });
Route::resource('datatable', 'AdminPostsController');
Route::get('delete/{id}', 'AdminPostsController@destroy');
Route::get('update/{id}', 'AdminPostsController@update');
// category panel
Route::get('cat/{category}', 'PostsCategoryController@show');
Route::get('query', 'PostsController@create');

Route::get('registration', 'PostsController@regis');
// Route::get('registration', function () { 
// 	$postsre = Posts::distinct()->get('category');  
// 	return view('registration', compact('postsre')); 
// });

resources/views/admin/edv/create.blade.php
@extends('admin.master_edv')

@section('content')
	<div class="container-full">
		<div class="content-header">
			<div class="d-flex align-items-center">
				<div class="mr-auto">
					<h3 class="page-title">Data Tables</h3>
					<div class="d-inline-block align-items-center">
						<nav>
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="{{ url('admin') }}"><i class="mdi mdi-home-outline"></i></a></li>
								<li class="breadcrumb-item" aria-current="page">Tables</li>
								<li class="breadcrumb-item" aria-current="page">Data Tables</li>
								<li class="breadcrumb-item active" aria-current="page">Create New Data</li>
							</ol>
						</nav>
					</div>
				</div>
			</div>
		</div>
		<section class="content">
			<div class="box">
				<div class="box-header with-border">
					<h3 class="box-title">Create New Data</h3>
				</div>
				<div class="box-body">
					<form method="post" action="{{url('datatable')}}">
						{{csrf_field()}}
						<div class="form-group">
							<h3>Title</h3>
							<input type="text" name="title" class="form-control"/>
						</div>
						<div class="form-group">
							<h3>Category</h3>
							<input type="text" name="category" class="form-control"/>
						</div>
						<div class="form-group">
							<h3>Content</h3>
							<textarea id="compose-textarea" name="content" class="form-control" style="height: 150px">
							</textarea>
						</div>
						<div class="form-group">
							<h3>Slug</h3>
							<input type="text" name="slug" class="form-control"/>
						</div>
						<div class="form-group">
							<h3>Embed</h3>
							<input type="text" name="embed" class="form-control"/>
						</div>
						<div class="form-group">
							<h3>Publisher</h3>
							<input type="text" name="publisher" class="form-control"/>
						</div>
						<div class="form-group">
							<h3>Viewed</h3>
							<input type="text" name="viewed" value="0" class="form-control"/>
						</div>
						<div class="form-group">
							<h3>Summary Content</h3>
							<textarea id="compose-textarea1" name="cont_sum" class="form-control" style="height: 150px">
							</textarea>
						</div>
						<!-- <div class="box-footer">
							<div class="pull-right">
								<button type="submit" class="btn btn-rounded btn-success"><i class="fa fa-envelope-o"></i> Submit</button>
							</div>
							<a href="{{ url('datatable') }}" class="btn btn-rounded btn-danger"><i class="fa fa-times"></i> Discard</a>
						</div> -->
						<div class="form-group">
							<input type="submit" class="btn btn-rounded btn-success" />
						</div>
					</form>
				</div>
				
			</div>
		</section>
	</div>
@endsection

resources/views/admin/edv/dashboard_data.blade.php
@extends('admin.master_edv')

@section('content')
	<div class="container-full">
		<div class="content-header">
			<div class="d-flex align-items-center">
				<div class="mr-auto">
					<h3 class="page-title">Data Tables</h3>
					<div class="d-inline-block align-items-center">
						<nav>
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="{{ url('admin') }}"><i class="mdi mdi-home-outline"></i></a></li>
								<li class="breadcrumb-item" aria-current="page">Tables</li>
								<li class="breadcrumb-item active" aria-current="page">Data Tables</li>
							</ol>
						</nav>
					</div>
				</div>
				<div class="right-title">
					<a href="{{route('datatable.create')}}" class="btn btn-info no-caret" type="button">Add New Item <i class="mdi mdi-plus"></i></a>
				</div>
			</div>
		</div>

		<section class="content">
			<div class="row">
				<div class="col-12">
					<div class="box">
						<div class="box-header with-border">
							<h3 class="box-title">Hover Export Data Table</h3>
							<h6 class="box-subtitle">Export data to Copy, CSV, Excel, PDF & Print</h6>
							<!-- <a href="{{ route('datatable.create') }}" class="btn btn-info btn-sm right">New News</a> -->
    
						   <!--  @if ($message = Session::get('message'))
						        <div class="alert alert-success martop-sm">
						            <p>{{ $message }}</p>
						        </div>
						    @endif -->
						</div>
						<!-- <div class="box-header with-border">
							
						</div> -->
						<div class="box-body">
							<div class="table-responsive">
								<table id="example" class="table table-bordered table-hover display nowrap margin-top-10 w-p100">
									<thead>
										<tr>
											<th>Action</th>
											<th>ID</th>
											<th>Title</th>
											<th>Category</th>
											<th>Content</th>
											<th>Slug</th>
											<th>Embed</th>
											<th>Publisher</th>
											<th>Viewed</th>
											<th>Created_at</th>
											<th>Updated_at</th>
											<th>Summary</th>
										</tr>
									</thead>
									@foreach($posts as $row)
									<tbody>
										<tr>
											<td class='text-center'>
												<a href="{{action('AdminPostsController@show', $row['id'])}}"><i class='fa fa-eye'></i></a>
												<a href="{{action('AdminPostsController@edit', $row['id'])}}"><i class='fa fa-pencil'></i></a>
												<a href="{{ url('delete') }}/{{ $row->id }}"><i class='fa fa-trash'></i></a>
											</td>
											<td>{{$row['id']}}</td>
											<td>{{$row['title']}}</td>
											<td>{{$row['category']}}</td>
											<td>{{$row['content']}}</td>
											<td>{{$row['slug']}}</td>
											<td>{{$row['embed']}}</td>
											<td>{{$row['publisher']}}</td>
											<td>{{$row['viewed']}}</td>
											<td>{{$row['created_at']}}</td>
											<td>{{$row['updated_at']}}</td>
											<td>{{$row['cont_sum']}}</td>
										</tr>
									</tbody>
									@endforeach				  
									<tfoot>
										<tr>
											<th>Action</th>
											<th>ID</th>
											<th>Title</th>
											<th>Category</th>
											<th>Content</th>
											<th>Slug</th>
											<th>Embed</th>
											<th>Publisher</th>
											<th>Viewed</th>
											<th>Created_at</th>
											<th>Updated_at</th>
											<th>Summary</th>
										</tr>
									</tfoot>
								</table>
							</div>              
						</div>
					</div>
				</div>
			</div>
		</section>
	</div>
@endsection

resources/views/admin/edv/edit.blade.php
@extends('admin.master_edv')

@section('content')
	<div class="container-full">
		<div class="content-header">
			<div class="d-flex align-items-center">
				<div class="mr-auto">
					<h3 class="page-title">Data Tables</h3>
					<div class="d-inline-block align-items-center">
						<nav>
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="{{ url('admin') }}"><i class="mdi mdi-home-outline"></i></a></li>
								<li class="breadcrumb-item" aria-current="page">Tables</li>
								<li class="breadcrumb-item" aria-current="page">Data Tables</li>
								<li class="breadcrumb-item active" aria-current="page">Edit Table</li>
							</ol>
						</nav>
					</div>
				</div>
			</div>
		</div>
		<section class="content">
			<div class="box">
				<div class="box-header with-border">
					<h3 class="box-title">Edit Table</h3>
				</div>
				<div class="box-body">
					<form method="patch" action="{{action('AdminPostsController@update', $id)}}">
					   	{{csrf_field()}}



					   	<div class="form-group">
							<h3>Title</h3>
							<input type="text" name="title" class="form-control" value="{{$posts->title}}"/>
						</div>
						<div class="form-group">
							<h3>Category</h3>
							<input type="text" name="category" class="form-control" value="{{$posts->category}}"/>
						</div>
						<div class="form-group">
							<h3>Content</h3>
							<textarea id="compose-textarea" name="content" class="form-control" style="height: 150px">
								{{$posts->content}}
							</textarea>
						</div>
						<div class="form-group">
							<h3>Slug</h3>
							<input type="text" name="slug" class="form-control" value="{{$posts->slug}}"/>
						</div>
						<div class="form-group">
							<h3>Embed</h3>
							<input type="text" name="embed" class="form-control" value="{{$posts->embed}}"/>
						</div>
						<div class="form-group">
							<h3>Publisher</h3>
							<input type="text" name="publisher" class="form-control" value="{{$posts->publisher}}"/>
						</div>
						<div class="form-group">
							<h3>Viewed</h3>
							<input type="text" name="viewed" class="form-control" value="{{$posts->viewed}}"/>
						</div>
						<div class="form-group">
							<h3>Summary Content</h3>
							<textarea id="compose-textarea1" name="cont_sum" class="form-control" style="height: 150px">
								{{$posts->cont_sum}}
							</textarea>
						</div>
						<div class="form-group box-footer">
							<div class="pull-right">
								<input type="submit" class="btn btn-rounded btn-success" value="Edit">
								<a href="{{ url('datatable') }}" class="btn btn-rounded btn-danger">Discard</a>
							</div>
						</div>
					   	<!-- <div class="form-group">
					    	<input type="submit" class="btn btn-primary" value="Edit" />
					   	</div> -->
					</form>
				</div>
			</div>
		</section>
	</div>
@endsection

resources/views/admin/edv/view.blade.php
@extends('admin.master_edv')

@section('content')
	<div class="container-full">
		<div class="content-header">
			<div class="d-flex align-items-center">
				<div class="mr-auto">
					<h3 class="page-title">Data Tables</h3>
					<div class="d-inline-block align-items-center">
						<nav>
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="{{ url('admin') }}"><i class="mdi mdi-home-outline"></i></a></li>
								<li class="breadcrumb-item" aria-current="page">Tables</li>
								<li class="breadcrumb-item" aria-current="page">Data Tables</li>
								<li class="breadcrumb-item active" aria-current="page">View Table</li>
							</ol>
						</nav>
					</div>
				</div>
			</div>
		</div>
		<section class="content">
			<div class="box">
				<div class="box-header with-border">
					<h3 class="box-title">View Data Id: {{$posts->id}}</h3>
				</div>
				<div class="box-body">
					<div class="row">
						<div class="col-lg-6">
							<div class="form-group">
								<h2>Title</h2>
								<h4 class="form-control-static">{{$posts->title}}</h4>
							</div>
							<div class="form-group">
								<h2>Category</h2>
								<h4 class="form-control-static">{{$posts->category}}</h4>
							</div>
							<div class="form-group">
								<h2>Content</h2>
								<h4 class="form-control-static">{{$posts->content}}</h4>
							</div>
							<div class="form-group">
								<h2>Slug</h2>
								<h4 class="form-control-static">{{$posts->slug}}</h4>
							</div>
							<div class="form-group">
								<h2>Embed</h2>
								<h4 class="form-control-static">{{$posts->embed}}</h4>
							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								<h2>Publisher</h2>
								<h4 class="form-control-static">{{$posts->publisher}}</h4>
							</div>
							<div class="form-group">
								<h2>Viewed</h2>
								<h4 class="form-control-static">{{$posts->viewed}}</h4>
							</div>
							<div class="form-group">
								<h2>Created_at</h2>
								<h4 class="form-control-static">{{$posts->created_at}}</h4>
							</div>
							<div class="form-group">
								<h2>Update_at</h2>
								<h4 class="form-control-static">{{$posts->update_at}}</h4>
							</div>
							<div class="form-group">
								<h2>Summary Content</h2>
								<h4 class="form-control-static">{{$posts->cont_sum}}</h4>
							</div>
						</div>
					</div>
				</div>
				<div class="box-footer">
					<div class="pull-right">
						<a href="{{action('AdminPostsController@edit', $posts['id'])}}" class="btn btn-rounded btn-success"><i class="fa fa-envelope-o"></i> Edit</a>
						<a href="{{ url('datatable') }}" class="btn btn-rounded btn-danger"><i class="fa fa-times"></i> Back</a>
					</div>
				</div>
			</div>
		</section>
	</div>
@endsection